### ISSUE TITLE
babel-preset-node6 is a dependency not a dev-dependency

### ISSUE THREAD

**Issue by entropitor** [devmetal/mock-async-storage#14]
I got erros when installing mock-async-storage because the .babelrc is included and it couldn't find the declared babel-preset-node6 as this is a devDependency and npm only installs normal dependencies

**Comment by devmetal** [comment]
How do you try install this package? I mean, if u want to use it normally for a native project, you have to just install via npm or yarn, i tried just now and its woking . Wich version of node/npm? Can you provide me the steps of your install process, or can you send me a stackrace?

**Comment by entropitor** [comment]
I did install it through npm but there is a `.babelrc` in the `node_modules` now, and my babel setup reads the babelrc which crashes my tests

**Comment by devmetal** [comment]
Wich version of node/npm do use?

**Comment by entropitor** [comment]
`npm -v`
5.6.0
`node -v`
v8.9.1

**Comment by bolandrm** [comment]
Same issue here, I had to install `babel-preset-node6` to get this to work.

**Comment by greyexpert** [comment]
Same here. It can be fixed by removing `.babelrc` from the library folder in `node_modules`. But it would be better to add `.babelrc` into `.npmignore`

**Comment by tpraxl** [comment]
Same here. Will this be fixed?

**Comment by devmetal** [comment]
Sorry for big delay :( Yes i will fix it soon as i can :) But feel to free for a pr :)

**Comment by devmetal** [comment]
I have to ask apologize, i sorry for this big delay :( Working and stuff... :D But really big thank you for support! And also feel to free create pr-s i will be glad and happy merge they :D
