### ISSUE TITLE
getItem should return null if key is not found?

### ISSUE THREAD

**Issue by bkkwok** [devmetal/mock-async-storage#17]
Doesn't React-Native's AsyncStorage getItem() return null if a key does not exist?

Your mock returns undefined, because you're using the Map()'s get api.

Makes a difference for code that rely on this specification.

**Comment by devmetal** [comment]
Hi, sorry for the delay. The documentation not mention about null or undefined. The function signature has a maybe result type. In the flow, it can be null or undefined. But if you say the original api returns null, i will check this, and i will fix this soon :) Also pr-s appreciated :) So feel to free, and thank you for support :)

**Comment by devmetal** [comment]
You have right. The api returns null. I will fix this :)

**Comment by devmetal** [comment]
Thank you again! 👍
