### ISSUE TITLE
Could not find d.ts file

### ISSUE THREAD

**Issue by jonathanpalma** [devmetal/mock-async-storage#25]
- mock-async-storage: 2.2.0
- typescript: 3.8.3

![image](https://user-images.githubusercontent.com/12414771/79375233-8cb60000-7f15-11ea-9857-21701237af63.png)

**Comment by jonathanpalma** [comment]
Sorry, I forgot to add that types are not under the DefinitelyTyped repository either

```shell
$ npm install -D @types/mock-async-storage
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fmock-async-storage - Not found
npm ERR! 404 
npm ERR! 404  '@types/mock-async-storage@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

```

**Comment by devmetal** [comment]
Hi, sorry i know i'm a bit late. I recently modernized the package. Now the ts definitions are included as well in the package.
