### ISSUE TITLE
`lib/` not included in latest release

### ISSUE THREAD

**Issue by SpaceK33z** [devmetal/mock-async-storage#4]
In the latest release, the `lib/` folder is missing. Since the `main` property in package.json refers to `lib/index.js`, this crashes the tests.

I'll make a pull request so it automatically includes the transpiled babel files when publishing, so this never happens again.

**Comment by devmetal** [comment]
Thank you for this help :) I published with your pr, pls report if its good and then we can close :)

**Comment by SpaceK33z** [comment]
It's fine now! Thank you!!
