### ISSUE TITLE
throwOnWrongReactAPI

### ISSUE THREAD

**Issue by TrekSoft** [devmetal/mock-async-storage#6]
When I run the example in the Readme, I get the same result as if I run it with the mock async storage library not loaded and mocking:

`    .../node_modules/react-native/Libraries/Utilities/throwOnWrongReactAPI.js: Unexpected token, expected , (15:33)
        13 | 'use strict';
        14 | 
      > 15 | function throwOnWrongReactAPI(key: string) {
           |                                  ^
        16 |   throw new Error(
       17 | Seems you're trying to access 'ReactNative.${key}' from the 'react-native' package. Perhaps you meant to access 'React.${key}' from the 'react' package instead?
        18 | `

**Comment by devmetal** [comment]
Thank you for feedback. I will fix this soon as i can :)

**Comment by devmetal** [comment]
@TrekSoft  Hi, can you provide me an example repository with this issue?

**Comment by TrekSoft** [comment]
Here you go - the versions I'm using of the various packages are:

"react": "15.4.2",
"react-native": "0.41.2",
"jest": "19.0.0",
"mock-async-storage": "1.0.3"

> import 'react-native';
> import { mock, release } from 'mock-async-storage'
> import React from 'react';
> 
> // Note: test renderer must be required after react-native.
> import renderer from 'react-test-renderer';
> 
> mock()
> 
> import { AsyncStorage as storage } from 'react-native'
> 
> it('Mock Async Storage working', () => {
>   storage.setItem('myKey', 'myValue').then(() => {
>       storage.getItem('myKey').then((value) => { expect(value).toBe('myValue'); });
>   });
> });

**Comment by TrekSoft** [comment]
Note that when I run the initial example in the README I get a complaint about async being before the anonymous function definition so maybe I need a babel preset to work with some newer code being used?

**Comment by devmetal** [comment]
If you use this in a react-native project by generated with the facebook tool, it has to working correctly.

Edited:

I found this on stackowerflow:
http://stackoverflow.com/questions/38184078/jest-rn-realm-error-cannot-find-module-throwonwrongreactapi-from-react

But at home i will check my example. Maybe they changed some things on thier api.

**Comment by TrekSoft** [comment]
Hmm - ok yeah I see that - running a fresh project I had no issues. Thanks - I'll check what I need to change on my main project.

**Comment by TrekSoft** [comment]
Aha! Yes the solution there installing the react native preset worked.
