### ISSUE TITLE
decouple from jest

### ISSUE THREAD

**Issue by adambene** [devmetal/mock-async-storage#7]
It is a nice package, but is tightly coupled with jest.
Loosely coupling would be a much better approach: not to depend on jest at all.

**Comment by devmetal** [comment]
Hi, please feel to free the check and suggestions about pr. Also i created the examples folder. Pls check that also. I need to upgrade the readme and link the new examples.

**Comment by adambene** [comment]
Hi, I like this PR. However the jest example or the readme should note how to mock `jest.mock('AsyncStorage', () => mockImpl)` and unmock `jest.unmock('AsyncStorage') `.

**Comment by devmetal** [comment]
I created a @beta version to npm for this improvement. You can try with npm install mock-async-storage@beta

**Comment by adambene** [comment]
Nice, thanks!
